trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: Install Bicep
  inputs:
    azureSubscription: 'BicepDeploymentConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az bicep install'

- task: AzureCLI@2
  displayName: Validate Dev Bicep
  inputs:
    azureSubscription: 'BicepDeploymentConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group validate --resource-group Blog --template-file infra/env/dev/main.bicep --parameters Code/main.parameters.json'

- task: CopyFiles@2
  displayName: Copy Code
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish Code
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
