trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2
      displayName: Install Bicep
      inputs:
        azureSubscription: 'BicepDeploymentConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az bicep install'

    - task: AzureCLI@2
      displayName: Validate Dev Bicep
      inputs:
        azureSubscription: 'BicepDeploymentConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az deployment sub create  --location westus --name dev-deploy01 --template-file infra/env/dev/main.bicep '

    - task: CopyFiles@2
      displayName: Copy Code
      inputs:
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish Code
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DEV
  jobs:
  - job: Deploy
    steps:
    - checkout: none
    
    - task: DownloadBuildArtifacts@0
      displayName: 'Download artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    
    - task: AzureCLI@2
      displayName: 'Deploy Bicep file'
      inputs:
        azureSubscription: 'BicepDeploymentConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
           --location westus --name dev-deploy01 \
           --template-file $(System.ArtifactsDirectory)/drop/infra/env/dev/main.bicep