trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: includeBuild
  type: boolean
  default: true
- name: includeService
  type: boolean
  default: true
- name: env
  type: string
  default: dev
  values: 
  - dev
  - uat
  - prod
- name: serviceName
  type: string
  default: rg
  values: 
  - rg
  - win_vm
  - webapp
- name:  location
  type: string
  default: 'westus'
- name: tags
  type: object
  default: {}
  displayName: 'tags'

variables:
  - template: services/pipeline/common/variable.yml
    parameters:
      env: ${{ parameters.env }}

stages:
- ${{ if parameters.includeBuild }}:
  - template: services/pipeline/common/build.yml
    parameters:
      env: ${{ parameters.env }}
      azureSubscription: ${{variables.azureSubscription}}
      serviceName: ${{ parameters.serviceName }}
      location: ${{ parameters.location }}

- ${{ if parameters.includeService }}:
  - template: services/pipeline/env/${{ parameters.env }}/${{ parameters.serviceName }}.yml
    parameters:
      env: ${{ parameters.env }}
      azureSubscription: ${{variables.azureSubscription}}
      serviceName: ${{ parameters.serviceName }}
      location: ${{ parameters.location }}