trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: includeBuild
  type: boolean
  default: true
- name: includeService
  type: boolean
  default: true
- name: env
  type: string
  default: dev
  values: 
  - dev
  - uat
  - prod
- name: serviceName
  type: string
  default: rg
  values: 
  - rg
  - win_vm
  - webapp
- name:  location
  type: string
  default: 'westus'

variables:
  - name: azureSubscription
    ${{ if eq( parameters['env'], 'dev') }}:
      value: "BicepDeploymentConnection"
    ${{ if eq( parameters['env'], 'uat' ) }}:
      value: "BicepDeploymentConnection"
    ${{ if notIn( parameters['env'], 'developer', 'prod') }}:
      value: "BicepDeploymentConnection"

stages:
- ${{ if parameters.includeBuild }}:
  - template: services/pipeline/config/build.yml
    parameters:
      env: ${{ parameters.env }}
      azureSubscription: ${{variables.azureSubscription}}
      serviceName: ${{ parameters.serviceName }}
      location: ${{ parameters.location }}

- ${{ if parameters.includeService }}:
  - template: services/pipeline/env/${{ parameters.env }}/${{ parameters.serviceName }}.yml
    parameters:
      env: ${{ parameters.env }}
      azureSubscription: ${{variables.azureSubscription}}
      serviceName: ${{ parameters.serviceName }}
      location: ${{ parameters.location }}