# build stage
parameters:
  env: 'dev'
  serviceName: 'rg'
  location: 'westus'
  azureSubscription: 'BicepDeploymentConnection'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2
      displayName: Install Bicep
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az bicep install'

    - task: AzureCLI@2
      displayName: Validate ${{ parameters.env }} Bicep
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub validate \
           --location ${{ parameters.location }} --name ${{ parameters.env }}-${{ parameters.serviceName }}-deploy01 \
           --template-file $(System.ArtifactsDirectory)/drop-${{ parameters.env }}-${{ parameters.serviceName }}/services/${{ parameters.serviceName }}/main.bicep \
           --parameters rgName=${{ parameters.rgName }} location=${{ parameters.location }}  taskId=${{ parameters.taskId }}

    - task: CopyFiles@2
      displayName: Copy Code
      inputs:
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish Code
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop-${{ parameters.env }}-${{ parameters.serviceName }}'
        publishLocation: 'Container'