# File: build-stage.yml
parameters:
  env: 'dev'
  serviceName: 'rg'
  location: 'westus'
  azureSubscription: 'BicepDeploymentConnection'

stages:
- stage: DEV
  jobs:
  - job: Deploy
    steps:
    - checkout: none
    
    - task: DownloadBuildArtifacts@0
      displayName: 'Download artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop-${{ parameters.env }}-${{ parameters.serviceName }}'
        downloadPath: '$(System.ArtifactsDirectory)'
    
    - task: AzureCLI@2
      displayName: 'Deploy Bicep file'
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
           --location ${{ parameters.location }} --name ${{ parameters.env }}-${{ parameters.serviceName }}-deploy01 \
           --template-file $(System.ArtifactsDirectory)/drop-${{ parameters.env }}-${{ parameters.serviceName }}/services/${{ parameters.serviceName }}/main.bicep
