trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: includeBuild
  type: boolean
  default: true
- name: env
  type: string
  default: dev
  values: 
  - dev
  - uat
  - prod
- name:  location
  type: string
  default: 'westus'
- name: rgName
  type: string
  default: ''
- name: taskId
  type: string
  default: ''
  displayName: 'Task or Ticket ID'

variables:
  - template: services/pipeline/common/variable.yml
    parameters:
      env: ${{ parameters.env }}

stages:
- ${{ if parameters.includeBuild }}:
  - template: services/pipeline/common/build.yml
    parameters:
      env: ${{ parameters.env }}
      azureSubscription: ${{variables.azureSubscription}}
      serviceName: ${{ parameters.serviceName }}
      location: ${{ parameters.location }}
      rgName: ${{ parameters.rgName }}
      taskId: ${{ parameters.taskId }}

- stage: '${{ parameters.env }}_${{ parameters.serviceName }}'
  jobs:
  - job: '${{ parameters.env }}_${{ parameters.serviceName }}_deploy'
    steps:
    - checkout: none
    
    - task: DownloadBuildArtifacts@0
      displayName: 'Download artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop-${{ parameters.env }}-${{ parameters.serviceName }}'
        downloadPath: '$(System.ArtifactsDirectory)'
    
    - task: AzureCLI@2
      displayName: 'Deploy Bicep file'
      inputs:
        azureSubscription: '${{ parameters.azureSubscription }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
           --location ${{ parameters.location }} --name ${{ parameters.env }}-${{ parameters.serviceName }}-deploy01 \
           --template-file $(System.ArtifactsDirectory)/drop-${{ parameters.env }}-${{ parameters.serviceName }}/services/${{ parameters.serviceName }}/main.bicep \
           --parameters rgName=${{ parameters.rgName }} location=${{ parameters.location }}  taskId=${{ parameters.taskId }}
